/**
 * BBW Regression-Calibrated Coefficients
 *
 * These coefficients are derived from OLS linear regression across all 3 BBW
 * seasons (1921, 1943, 1971), matching 535 non-pitcher batters to their Lahman
 * stats. Each coefficient maps a Lahman stat rate to a BBW card value count:
 *
 *   card_count = SLOPE * lahman_rate + INTERCEPT
 *
 * This replaces the ad-hoc constants (CARD_K_FACTOR, CARD_DOUBLES_FACTOR,
 * suppression compensation) that were previously used in value-mapper.ts.
 *
 * Generated by: tests/unit/lib/bbw/multi-season-calibration.test.ts
 */

/**
 * Regression slopes: how many card positions per unit of Lahman rate.
 *
 * For context, a rate of 0.10 (10% of PA) with slope 10 = 1 card position.
 * The old formula used TOTAL_DRAWABLE (24) as the slope for most outcomes.
 */
export const CALIBRATED_SLOPES = {
  walk: 9.9154,
  strikeout: 3.5879,
  homeRun: 36.9178,
  single: 27.1540,
  double: 33.4504,
  triple: 19.5232,
} as const;

/**
 * Regression intercepts: base card positions regardless of rate.
 *
 * Non-zero intercepts mean BBW assigns a minimum number of positions even
 * for players with zero rate (e.g., every batter gets ~2 K positions on the
 * card even with low strikeout rate, because the pitcher grade gate produces
 * additional Ks during simulation).
 */
export const CALIBRATED_INTERCEPTS = {
  walk: 1.7512,
  strikeout: 2.6213,
  homeRun: 0.5750,
  single: 2.0088,
  double: 0.1758,
  triple: 0.3631,
} as const;

/**
 * Maximum pitcher grade. BBW uses grades 1-22, not the 1-15 that was
 * previously assumed. Grades > 15 always win the grade gate roll
 * (R2 in [1,15]), providing 100% suppression.
 */
export const MAX_PITCHER_GRADE = 22;

/**
 * Calibrated power rating tiers from BBW card[24] vs Lahman ISO analysis.
 *
 * BBW power ratings show weak linear correlation with ISO (r=-0.17), suggesting
 * BBW uses era-relative power assignment or a different metric. The mode-based
 * tiers below are derived from the most common BBW power value in each ISO bucket.
 *
 * Values are IDT-active [13-21] per APBA specification:
 *   13 = none, 15 = minimal, 16 = below avg, 17 = average,
 *   18 = above avg, 19 = good, 20 = very good, 21 = excellent
 */
export const CALIBRATED_POWER_TIERS: readonly { maxISO: number; cardValue: number; label: string }[] = [
  { maxISO: 0.050, cardValue: 18, label: 'No power (BBW mode: 18)' },
  { maxISO: 0.080, cardValue: 18, label: 'Minimal (BBW mode: 18)' },
  { maxISO: 0.110, cardValue: 18, label: 'Below average (BBW mode: 18)' },
  { maxISO: 0.150, cardValue: 20, label: 'Average (BBW mode: 20)' },
  { maxISO: 0.190, cardValue: 20, label: 'Above average (BBW mode: 20)' },
  { maxISO: 0.230, cardValue: 20, label: 'Good (BBW mode: 20)' },
  { maxISO: 0.280, cardValue: 20, label: 'Very good (BBW mode: 20)' },
  { maxISO: Infinity, cardValue: 21, label: 'Excellent' },
];

/**
 * Calibrated archetype thresholds from BBW distribution analysis.
 *
 * Best F1 for power archetype detection: HR >= 18 OR ISO >= 0.170 (F1 = 0.805).
 * Current thresholds: HR >= 25 OR ISO >= 0.230 are too conservative.
 */
export const CALIBRATED_ARCHETYPE = {
  powerHRThreshold: 18,
  powerISOThreshold: 0.170,
  speedSBThreshold: 20,   // Keep current -- matches BBW well
  contactSpeedBAThreshold: 0.280, // Keep current
  contactSpeedSBThreshold: 10,    // Keep current
} as const;
