/**
 * Error Code Constants
 *
 * REQ-ERR-002: Typed error codes for all application domains.
 *
 * Each code follows the pattern: ERR_{DOMAIN}_{DESCRIPTION}
 * Layer 0: Pure data, no logic.
 */

export const ERROR_CODES = {
  // Auth domain
  AUTH_TOKEN_EXPIRED: 'ERR_AUTH_TOKEN_EXPIRED',
  AUTH_NOT_COMMISSIONER: 'ERR_AUTH_NOT_COMMISSIONER',
  AUTH_UNAUTHORIZED: 'ERR_AUTH_UNAUTHORIZED',

  // Draft domain
  DRAFT_PLAYER_TAKEN: 'ERR_DRAFT_PLAYER_TAKEN',
  DRAFT_OUT_OF_TURN: 'ERR_DRAFT_OUT_OF_TURN',
  DRAFT_NOT_STARTED: 'ERR_DRAFT_NOT_STARTED',
  DRAFT_COMPLETED: 'ERR_DRAFT_COMPLETED',

  // League domain
  LEAGUE_INVALID_TRANSITION: 'ERR_LEAGUE_INVALID_TRANSITION',
  LEAGUE_NOT_FOUND: 'ERR_LEAGUE_NOT_FOUND',
  LEAGUE_INVALID_INVITE: 'ERR_LEAGUE_INVALID_INVITE',
  LEAGUE_FULL: 'ERR_LEAGUE_FULL',

  // Roster domain
  ROSTER_COMPOSITION: 'ERR_ROSTER_COMPOSITION',
  ROSTER_DUPLICATE_PLAYER: 'ERR_ROSTER_DUPLICATE_PLAYER',

  // Schedule domain
  SCHEDULE_INVALID_TEAM_COUNT: 'ERR_SCHEDULE_INVALID_TEAM_COUNT',
  SCHEDULE_NO_TEAMS: 'ERR_SCHEDULE_NO_TEAMS',

  // Playoff domain
  PLAYOFF_INSUFFICIENT_TEAMS: 'ERR_PLAYOFF_INSUFFICIENT_TEAMS',
  PLAYOFF_SERIES_COMPLETE: 'ERR_PLAYOFF_SERIES_COMPLETE',

  // Validation domain
  VALIDATION_FAILED: 'ERR_VALIDATION_FAILED',

  // Simulation domain
  SIMULATION_FAILED: 'ERR_SIMULATION_FAILED',

  // Data domain
  DATA_NOT_FOUND: 'ERR_DATA_NOT_FOUND',
  DATA_INTEGRITY: 'ERR_DATA_INTEGRITY',

  // External domain
  EXTERNAL_SERVICE: 'ERR_EXTERNAL_SERVICE',

  // AI/Claude domain
  CLAUDE_TIMEOUT: 'ERR_CLAUDE_TIMEOUT',
  CLAUDE_MALFORMED: 'ERR_CLAUDE_MALFORMED',
  CLAUDE_UNAVAILABLE: 'ERR_CLAUDE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
